---
- name: Configure Lag-Group for Node
  hosts: ta5k  
  gather_facts: no
  become: yes

  tasks:
    - name: Configure Lag-Group if directly connected to a router
      ios_config:
        lines:
          - interface lag-group 1/A/1
          - alias "UPLINK_TO_RTR"
          - cross-slot
          - link ten-gigabit-ethernet 1/A/1
          - link ten-gigabit-ethernet 1/B/1
          - interface ten-gigabit-ethernet 1/A/1
          - no shutdown
          - lacp mode active
          - lldp disable
          - interface ten-gigabit-ethernet 1/B/1
          - no shutdown
          - lacp mode active
          - lldp disable
          - ethernet default interface lag-group 1/A/1