---
- name: Configure Regular Connection for Node
  hosts: ta5k  
  gather_facts: no
  become: yes

  tasks:
    - name: Determine if the node connects upstream to another TA5K
      ios_command:
        commands: show node
      register: node_info

    - name: Configure Regular Connection if connecting upstream to another TA5K
      ios_config:
        lines:
          - interface ten-gigabit-ethernet 1/A/1
          - no shutdown
          - interface ten-gigabit-ethernet 1/B/1
          - no shutdown
          - ethernet default interface ten-gigabit-ethernet 1/A/1
        when: node_info.stdout_lines[0] is search("connects upstream to another TA5K")
