---
- name: Configure Regular Connection for Node
  hosts: ta5k  
  gather_facts: no
  become: no

  tasks:
    - name: Configure Regular Connection if connecting upstream to another TA5K
      ios_command:
        commands:
          - conf t
          - interface ten-gigabit-ethernet 1/A/1
          - no shutdown
          - interface ten-gigabit-ethernet 1/B/1
          - no shutdown
          - ethernet default interface ten-gigabit-ethernet 1/A/1