---
- name: Configure Cisco Router
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Configure multicast-routing
      ios_command:
        commands:
          - configure terminal
          - multicast-routing
          - address-family ipv4
          - interface Bundle-Ether402
          - enable
          - exit
          - interface Bundle-Ether403
          - enable
          - exit
          - interface Bundle-Ether400.400
          - enable
          - exit
          - interface Bundle-Ether400.401
          - enable
          - exit
          - interface Bundle-Ether400.402
          - enable
          - exit
          - interface Bundle-Ether400.403
          - enable
          - exit
          - interface Bundle-Ether400.404
          - enable
          - exit
          - interface Bundle-Ether400.405
          - enable
          - exit
          - interface Bundle-Ether400.406
          - enable
          - exit
          - interface Bundle-Ether400.408
          - enable
          - exit
          - interface Bundle-Ether400.409
          - enable
          - exit
          - ssm range SSMv2
          - rate-per-route
          - accounting per-prefix
          - exit
          - exit
          - commit best-effort