---
- name: Configure Cisco Router
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Configure OSPF
      ios_command:
        commands:
          - configure terminal
          - router ospf 1
          - nsr
          - log adjacency changes detail
          - router-id 10.0.0.10
          - segment-routing mpls
          - bfd minimum-interval 50
          - bfd fast-detect
          - bfd multiplier 3
          - passive enable
          - segment-routing forwarding mpls
          - mpls ldp sync
          - nsf ietf
          - segment-routing sr-prefer
          - area 0
          - mpls traffic-eng
          - interface Bundle-Ether400.400
          - exit
          - interface Bundle-Ether400.401
          - exit
          - interface Bundle-Ether400.402
          - exit
          - interface Bundle-Ether400.403
          - exit
          - interface Bundle-Ether400.404
          - exit
          - interface Bundle-Ether400.405
          - exit
          - interface Bundle-Ether400.406
          - exit
          - interface Bundle-Ether400.408
          - exit
          - interface Bundle-Ether400.409
          - exit
          - interface Bundle-Ether400.410
          - exit
          - interface Bundle-Ether402
          - bfd minimum-interval 15
          - bfd fast-detect
          - bfd multiplier 3
          - network point-to-point
          - passive disable
          - dead-interval 3
          - hello-interval 1
          - exit
          - interface Bundle-Ether403
          - bfd minimum-interval 15
          - bfd fast-detect
          - bfd multiplier 3
          - network point-to-point
          - passive disable
          - dead-interval 3
          - hello-interval 1
          - exit
          - interface Loopback0
          - prefix-sid index 110
          - exit
          - exit
          - commit best-effort