---
- name: Change Banner
  hosts: routers
  gather_facts: no
  become: yes

  vars:
    motd_message: |
      banner motd ^C
           _____   _       _____    ____
          |_   _| | |     |_   _|  / ___|
            | |   | |       | |   | |
            | |   | |___    | |   | |___
            |_|   |_____|   |_|    \____|
      -----------------------------------------------------------
      -------------
      W A R N I N G
      -------------
      Unauthorized access prohibited
      Disconnect IMMEDIATELY if you are not an authorized user!
      -----------------------------------------------------------
      Unauthorized use may subject you to criminal prosecution.
      Evidence of any such unauthorized use collected during
      monitoring may be used for administrative, criminal or
      other adverse action. Use of this system constitutes
      consent to monitoring for these purposes.
      -----------------------------------------------------------
      ^C
      
  tasks:
    - name: Update Banner
      ios_config:
        lines: 
          - {{motd_message}}

      register: show_running_configuration_output

    - name: Display show run output
      debug:
        var: show_running_configuration_output.stdout_lines