---
- name: Backup Cisco Router Running Configuration
  hosts: routers  # Replace with the hostname or group name for your router(s)
  gather_facts: yes

  tasks:
    # - name: Gather running configuration
    #   ios_command:
    #     commands:
    #       - show running-config
    #   register: running_config
    #   become: no  # Use 'yes' if you need elevated privileges

    - name: gather hostname
      iosxr_hostname:
        state: gathered
      register: hostname
      become: no  # Use 'yes' if you need elevated privilege

    - name: Display Hostname
      debug:
        var: hostname.stdout_lines

    # - name: Save running configuration to a file
    #   copy:
    #     content: "{{ structured_config }}"
    #     dest: "/etc/ansible/router_backup_configurations/{{ hostname }}_running_config.cfg"
    #   when: running_config is defined
    #   become: no