---
- name: Backup Cisco Router Running Configuration
  hosts: routers  # Replace with the hostname or group name for your router(s)
  gather_facts: no

  tasks:
    - name: Gather running configuration
      ios_command:
        commands:
          - show running-config
      register: running_config
      become: no  # Use 'yes' if you need elevated privileges

    - name: Save running configuration to a file
      debug:
        var: running_config.stdout_lines
      copy:
        content: "{{ running_config.stdout_lines }}"
        dest: "/etc/ansible/router_backup_configurations/routers_running_config.cfg"
      when: running_config is defined
      become: no