---
- name: Backup Cisco Router Running Configuration
  hosts: routers  # Replace with the hostname or group name for your router(s)
  gather_facts: yes

  tasks:
    - name: Gather running configuration
      ios_command:
        commands:
          - show running-config
      register: running_config
      become: no  # Use 'yes' if you need elevated privileges

    - name: Gather hostname
      ios_command:
        commands:
          - show running-config | include hostname
      register: hostname
      become: no

    - name: Extract hostname
      set_fact:
        router_hostname: "{{ hostname.stdout_lines[0].split(' ')[1] }}"
      when: hostname.stdout_lines | length > 0

    - name: Display Hostname
      debug:
        var: router_hostname
    # - name: Save running configuration to a file
    #   copy:
    #     content: "{{ structured_config }}"
    #     dest: "/etc/ansible/router_backup_configurations/{{ hostname }}_running_config.cfg"
    #   when: running_config is defined
    #   become: no