---
- name: Configure L2VPN on Connection back to AT&T's network
  hosts: routers
  gather_facts: no
  become: no
  
  tasks:
    - name: Configure L2VPN
      ios_config:
        lines:
          - interface GigabitEthernet0/2/0/1.2139 l2transport
          - encapsulation dot1q 2139
          - rewrite ingress tag pop 1 symmetric
          - mtu 1518
          - exit
          - l2vpn
          - xconnect group MetroE
          - p2p TDOT_PICKETT_BYTW_2139
          - interface GigabitEthernet0/1/0/2.2139
          - neighbor ipv4 10.0.0.10 pw-id 2139
          - exit
          - exit
          - exit
          - exit
          - commit best-effort          
        parents: interface GigabitEthernet0/1/0/2.2139