---
- name: Show OSPF Neighbor
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Execute show ospf neighbor
      ios_command:
        commands: "show ospf neighbor"
      register: show_running_configuration_output

    - name: Display show run output
      debug:
        var: show_running_configuration_output.stdout_lines