---
- name: Show inventory
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Execute Show Inventory
      ios_command:
        commands: "show inventory"
      register: show_running_configuration_output

    - name: Display Show Inventory
      debug:
        var: show_running_configuration_output.stdout_lines
