---
- name: Show Route
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Execute show route
      ios_command:
        commands: "show route"
      register: show_running_configuration_output

    - name: Display show run output
      debug:
        var: show_running_configuration_output.stdout_lines