---
- name: Gather information about L2VPN bridge domains
  hosts: routers
  gather_facts: yes
  connection: network_cli

  tasks:
    - name: Execute Show L2VPN Bridge-Domain
      ios_command:
        commands:
          - show l2vpn bridge-domain
      register: l2vpn_bridge_domain_output

    - name: Display the Output
      debug:
        var: l2vpn_bridge_domain_output.stdout_lines
