---
- name: Show MPLS LDP Neighbor
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Execute Show MPLS LDP Neighbor
      ios_command:
        commands: "show mpls ldp neighbor"
      register: show_running_configuration_output

    - name: Display show run output
      debug:
        var: show_running_configuration_output.stdout_lines