---
- name: Gather routing table information
  hosts: routers
  gather_facts: yes
  
  tasks:
    - name: Run the "show route" command
      ios_command:
        commands: "show ip route"
      register: route_output

    - name: Display the output
      debug:
        var: route_output.stdout_lines
