---
- name: Show BGP Neighbor Brief
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Execute Show BGP Neighbor Brief
      ios_command:
        commands: "show bgp neighbor brief"
      register: show_running_configuration_output

    - name: Display show run output
      debug:
        var: show_running_configuration_output.stdout_lines