---
- name: Show l2vpn xconnect
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Execute Show L2VPN XConnect
      ios_command:
        commands: "show l2vpn xconnect"
      register: show_running_configuration_output

    - name: Display Show L2VPN XConnect
      debug:
        var: show_running_configuration_output.stdout_lines
