---
- name: Configure Cisco Router
  hosts: cisco_router
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Apply Interface Configuration
      ios_config:
        lines:
          - interface Bundle-Ether400.2139 l2transport
          - encapsulation dot1q 2139
          - rewrite ingress tag pop 1 symmetric
          - mtu 1518
        parents: interface Bundle-Ether400.2139
      when: ansible_network_os == 'ios'

    - name: Apply L2VPN Configuration
      ios_config:
        lines:
          - l2vpn
          - xconnect group MetroE
          - p2p TDOT_PICKETT_2139
          -   interface Bundle-Ether400.2139
          -   neighbor ipv4 10.0.0.1 pw-id 2139
        parents: l2vpn
      when: ansible_network_os == 'ios'

