---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Configure AAA group server radius & Authentication Login
      ios_command:
        commands:
          - conf t 
          - aaa group server radius twlakes1
          - vrf netmgt
          - server-private 192.168.150.4 auth-port 1645 acct-port 1646
          - server-private 192.168.150.5 auth-port 1645 acct-port 1646
          - source-interface Loopback1
          - exit
          - aaa authentication login default group twlakes local
          - commit
