---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: yes

  tasks:
    - name: Configure interface Bundle-Ether400
      ios_command:
        commands:
          - interface Bundle-Ether400
          - description "Downlink to AGSW Cluster"
          - mtu 9216
          - exit
