---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Configure Interface Bundle-Ether400
      ios_command:
        commands:
          - conf t
          - interface Bundle-Ether400
          - description "Downlink to AGSW Cluster"
          - mtu 9216
          - exit
