---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no
  connection: network_cli
  
  tasks:
    - name: Enable CDP
      ios_command:
        commands: conf t && cdp run

