# ---
# - name: Update Cisco Router Configuration
#   hosts: routers
#   gather_facts: no
#   become: no

#   tasks:
#     - name: Configure Class Map for Network Management Traffic
#       ios_command:
#         commands:
#           - conf t
#           - class-map match-any cmap-mgmt-dscp
#           - description "Network Mangement Traffic Class"
#           - match dscp cs7
#           - match mpls experimental topmost 7
#           - end

#     - name: Configure Class Map for Video Traffic
#       ios_command:
#         commands:
#           - class-map match-any cmap-video-dscp
#           - description Video Traffic Class
#           - match dscp af41 cs4
#           - end

#     - name: Configure Class Map for Voice Traffic
#       ios_command:
#         commands:
#           - class-map match-any cmap-voice-dscp
#           - match dscp ef cs5
#           - end

#     - name: Configure Class Map for Control Traffic
#       ios_command:
#         commands:
#           - class-map match-any cmap-control-dscp
#           - description Control Traffic Class
#           - match dscp cs6
#           - match mpls experimental topmost 6
#           - end

#     - name: Configure Class Map for VoIP Real-Time Traffic
#       ios_command:
#         commands:
#           - class-map match-any cmap-voip-rt-dscp
#           - description VoIP Traffic Class
#           - match dscp ef
#           - match mpls experimental topmost 5
#           - end

# ---
# - name: Update Cisco Router Configuration
#   hosts: routers
#   gather_facts: no
#   become: no

#   tasks:
#     - name: Configure Class Map for Network Management Traffic
#       ios_config:
#         lines:
#           - class-map match-any cmap-mgmt-dscp
#           - description "Network Management Traffic Class"
#           - match dscp cs7
#           - match mpls experimental topmost 7

#     - name: Configure Class Map for Video Traffic
#       ios_config:
#         lines:
#           - class-map match-any cmap-video-dscp
#           - description Video Traffic Class
#           - match dscp af41 cs4

#     - name: Configure Class Map for Voice Traffic
#       ios_config:
#         lines:
#           - class-map match-any cmap-voice-dscp
#           - match dscp ef cs5

#     - name: Configure Class Map for Control Traffic
#       ios_config:
#         lines:
#           - class-map match-any cmap-control-dscp
#           - description Control Traffic Class
#           - match dscp cs6
#           - match mpls experimental topmost 6

#     - name: Configure Class Map for VoIP Real-Time Traffic
#       ios_config:
#         lines:
#           - class-map match-any cmap-voip-rt-dscp
#           - description VoIP Traffic Class
#           - match dscp ef
#           - match mpls experimental topmost 5

---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Configure Class Maps Net Management
      ios_command:
        commands:
          - conf t
          - class-map match-any cmap-mgmt-dscp
          - description "Network Management Traffic Class"
          - match dscp cs7
          - match mpls experimental topmost 7
          - end-class-map

    - name: Configure Class Maps Video
      ios_command:
        commands:
          - class-map match-any cmap-video-dscp
          - description Video Traffic Class
          - match dscp af41 cs4
          - end-class-map

    - name: Configure Class Maps Voice
      ios_command:
        commands:          
          - class-map match-any cmap-voice-dscp
          - match dscp ef cs5
          - end-class-map

    - name: Configure Class Maps Control Traffic Class
      ios_command:
        commands:
          - class-map match-any cmap-control-dscp
          - description Control Traffic Class
          - match dscp cs6
          - match mpls experimental topmost 6
          - end-class-map

    - name: Configure Class Maps VoIP
      ios_command:
        commands:
          - class-map match-any cmap-voip-rt-dscp
          - description VoIP Traffic Class
          - match dscp ef
          - match mpls experimental topmost 5
          - end-class-map

