---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Configure Class Maps Net Management
      ios_command:
        commands:
          - conf t
          - class-map match-any cmap-mgmt-dscp
          - description "Network Management Traffic Class"
          - match dscp cs7
          - match mpls experimental topmost 7
          - end-class-map

          - class-map match-any cmap-video-dscp
          - description Video Traffic Class
          - match dscp af41 cs4
          - end-class-map

          - class-map match-any cmap-voice-dscp
          - match dscp ef cs5
          - end-class-map

          - class-map match-any cmap-control-dscp
          - description Control Traffic Class
          - match dscp cs6
          - match mpls experimental topmost 6
          - end-class-map

          - class-map match-any cmap-voip-rt-dscp
          - description VoIP Traffic Class
          - match dscp ef
          - match mpls experimental topmost 5
          - end-class-map

