---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no
  
  tasks:
    - name: Configure HW-module Profile for Location 0/0/CPU0
      ios_command:
        commands:
          - conf t
          - hw-module profile itcam to-profile-se1 location 0/0/CPU0

    - name: Configure HW-module Profile for Location 0/1/CPU0
      ios_command:
        commands:
          - hw-module profile itcam to-profile-se1 location 0/1/CPU0