---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: yes
  
  tasks:
    - name: Configure hw-module profile for location 0/0/CPU0
      ios_command:
        commands:
          - hw-module profile itcam to-profile-se1 location 0/0/CPU0
          - exit

    - name: Configure hw-module profile for location 0/1/CPU0
      ios_command:
        commands:
          - hw-module profile itcam to-profile-se1 location 0/1/CPU0
          - exit
