---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no

  tasks:
      - name: Configure Hostname/Taskgroup/Timezone
        ios_command:
          commands:
            - conf t
            - hostname ASR-BYTW-10
            # Default Taskgroup
            - aaa default-taskgroup root-lr
            # Timezone
            - clock timezone CST America/Chicago
            - commit best-effort
