# ---
# - name: Update Cisco Router Configuration
#   hosts: routers
#   gather_facts: no
#   become: no

#   tasks:
#     - name: Configure hostname
#       ios_command:
#         commands:
#           - conf t
#           - hostname ASR-BYTW-10

#     - name: Configure AAA
#       ios_command:
#         commands:
#           - aaa default-taskgroup root-lr

#     - name: Configure clock timezone
#       ios_command:
#         commands:
#           - clock timezone CST America/Chicago

#     - name: Configure logging
#       ios_command:
#         commands:
#           - logging trap informational
#           - logging console disable
#           - logging monitor disable
#           - logging buffered debugging
#           - logging 10.2.0.10 vrf netmgt severity info port default
#           - logging 10.2.0.12 vrf netmgt severity info port default
#           - logging 10.2.0.13 vrf netmgt severity info port default
#           - logging source-interface Loopback1 vrf netmgt

#     - name: Configure service timestamps
#       ios_command:
#         commands:
#           - service timestamps log datetime localtime msec show-timezone
#           - service timestamps debug datetime localtime msec show-timezone

#     - name: Configure domain and name servers
#       ios_command:
#         commands:
#           - domain vrf netmgt name-server 192.168.150.2
#           - domain vrf netmgt name-server 192.168.150.3
#           - domain name TWLAKES.LOCAL
---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Configure hostname
      ios_command:
        commands:
          - conf t
          - hostname ASR-BYTW-10
      check_mode: yes

    - name: Configure AAA
      ios_command:
        commands:
          - aaa default-taskgroup root-lr
      check_mode: yes

    - name: Configure clock timezone
      ios_command:
        commands:
          - clock timezone CST America/Chicago
      check_mode: yes

    - name: Configure logging
      ios_command:
        commands:
          - logging trap informational
          - logging console disable
          - logging monitor disable
          - logging buffered debugging
          - logging 10.2.0.10 vrf netmgt severity info port default
          - logging 10.2.0.12 vrf netmgt severity info port default
          - logging 10.2.0.13 vrf netmgt severity info port default
          - logging source-interface Loopback1 vrf netmgt
      check_mode: yes

    - name: Configure service timestamps
      ios_command:
        commands:
          - service timestamps log datetime localtime msec show-timezone
          - service timestamps debug datetime localtime msec show-timezone
      check_mode: yes

    - name: Configure domain and name servers
      ios_command:
        commands:
          - domain vrf netmgt name-server 192.168.150.2
          - domain vrf netmgt name-server 192.168.150.3
          - domain name TWLAKES.LOCAL
      check_mode: yes
