---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no

  tasks:
      - name: Configure Hostname/Taskgroup/Timezone
        ios_command:
          commands:
            - conf t
            - hostname ASR-BYTW-10
            # Default Taskgroup
            - aaa default-taskgroup root-lr
            # Timezone
            - clock timezone CST America/Chicago
            - commit best-effort
            
    # - name: Configure Logging
    #   ios_command:
    #     commands:
    #       - logging trap informational
    #       - logging console disable
    #       - logging monitor disable
    #       - logging buffered debugging
    #       - logging 10.2.0.10 vrf netmgt severity info port default
    #       - logging 10.2.0.12 vrf netmgt severity info port default
    #       - logging 10.2.0.13 vrf netmgt severity info port default
    #       - logging source-interface Loopback1 vrf netmgt

    # - name: Configure Service Timestamps
    #   ios_command:
    #     commands:
    #       - service timestamps log datetime localtime msec show-timezone
    #       - service timestamps debug datetime localtime msec show-timezone

    # - name: Configure Domain and Name Servers
    #   ios_command:
    #     commands:
    #       - domain vrf netmgt name-server 192.168.150.2
    #       - domain vrf netmgt name-server 192.168.150.3
    #       - domain name TWLAKES.LOCAL
