---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: yes

  tasks:
    - name: Configure Loopback0 interface
      ios_command:
        commands:
          - interface Loopback0
          - description MPLS/HSD/RID
          - ipv4 address 10.0.0.10 255.255.255.255
          - exit

    - name: Configure Loopback1 interface
      ios_command:
        commands:
          - interface Loopback1
          - description Management
          - vrf netmgt
          - ipv4 address 10.0.1.10 255.255.255.255
          - exit

    - name: Configure Loopback3 interface
      ios_command:
        commands:
          - interface Loopback3
          - description Voice RID
          - vrf voice
          - ipv4 address 10.0.3.10 255.255.255.255
          - exit
