# ---
# - name: Update Cisco Router Configuration
#   hosts: routers
#   gather_facts: no
#   become: no
#   connection: network_cli

#   tasks:
#     - name: Configure Policy Map for Access Out
#       ios_command:
#         commands:
#           - conf t
#           - policy-map pmap-access-out
#           - class cmap-voice-dscp
#           - bandwidth percent 10
#           - exit
#           - class cmap-video-dscp
#           - bandwidth 300 mbps
#           - exit
#           - class class-default
#           - exit
#           - exit

#     - name: Configure Policy Map for Core Egress
#       ios_command:
#         commands:
#           - policy-map pmap-core-egress
#           - class cmap-voip-rt-dscp
#           - police rate 5 gbps
#           - priority level 1
#           - exit
#           - class cmap-video-dscp
#           - bandwidth percent 30
#           - exit
#           - class cmap-mgmt-dscp
#           - bandwidth percent 5
#           - exit
#           - class cmap-control-dscp
#           - bandwidth percent 5
#           - exit
#           - class class-default
#           - exit
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no
  connection: network_cli

  tasks:
    - name: Configure policy map for Access Out
      cisco.ios.ios_config:
        lines:
          - policy-map pmap-access-out
          - class cmap-voice-dscp
          - bandwidth percent 10
          - exit
          - class cmap-video-dscp
          - bandwidth 300 mbps
          - exit
          - class class-default
          - exit
        parents: ['']
      become: yes

    - name: Configure policy map for Core Egress
      cisco.ios.ios_config:
        lines:
          - policy-map pmap-core-egress
          - class cmap-voip-rt-dscp
          - police rate 5 gbps
          - priority level 1
          - exit
          - class cmap-video-dscp
          - bandwidth percent 30
          - exit
          - class cmap-mgmt-dscp
          - bandwidth percent 5
          - exit
          - class cmap-control-dscp
          - bandwidth percent 5
          - exit
          - class class-default
          - exit
        parents: ['']
      become: yes

