---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Configure SNMP
      ios_command:
        commands:
          - conf t
          - snmp-server vrf netmgt
          - host 10.2.0.10 traps TLTC7609
          - host 10.2.0.10 traps TwinLakesCoreNetwork
          - host 10.2.0.11 traps TLTC7609
          - host 10.2.0.11 traps TwinLakesCoreNetwork
          - exit
          - snmp-server group snmp_admin v3 priv
          - snmp-server contact networking@twinlakes.net
          - snmp-server location [36.570583,-85.135065] 401 W Main St, Byrdstown, TN 38549