---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no # Enable privilege escalation if necessary
  connection: network_cli

  tasks:
    - name: Configure SSH Servers
      ios_command:
        commands:
          - conf t
          - ssh server v2
          - ssh server vrf netmgt