---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: yes

  tasks:
    - name: Configure SSH server for version 2
      ios_config:
        lines:
          - ssh server v2
          - exit

    - name: Configure SSH server using VRF netmgt
      ios_config:
        lines:
          - ssh server vrf netmgt
          - exit
