# ---
# - name: Update Cisco Router Configuration
#   hosts: routers
#   gather_facts: no
#   become: no  # Enable privilege escalation if necessary
#   connection: network_cli

#   tasks:
#     - name: Configure SSH server for version 2
#       ios_command:
#         commands:
#           - conf t
#           - ssh server v2

#     - name: Configure SSH server using VRF netmgt
#       ios_command:
#         commands:
#           - conf t
#           - ssh server vrf netmgt
---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no # Enable privilege escalation if necessary
  connection: network_cli

  tasks:
    - name: Configure SSH servers
      ios_command:
        commands:
          - conf t
          - ssh server v2
          - ssh server vrf netmgt