---
- name: Update Cisco Router Configuration
  hosts: routers
  gather_facts: no
  become: no

  tasks:
    - name: Configure SSH server for version 2
      ios_command:
        commands:
          - conf t
          - ssh server v2
          - exit

    - name: Configure SSH server using VRF netmgt
      ios_command:
        commands:
          - ssh server vrf netmgt
          - exit
