---
- name: Configure VRF for voice
  hosts: routers

  tasks:
    - name: Configure VRF for voice
      ios_config:
        lines:
          - vrf definition voice
          - rd 65001:1
          - address-family ipv4 unicast
          - label mode per-vrf
          - redistribute connected
          - exit
          - exit
          - exit
          - commit best-effort
