---
- name: Show Current Configuration
  hosts: ta5k
  gather_facts: no
  become: yes

  tasks:
    - name: Execute Show Run Command
      ios_command:
        commands: "show run"
      register: show_running_configuration_output

    - name: Display Show Run Output
      debug:
        var: show_running_configuration_output.stdout_lines
