---
- name: Show Current Configuration
  hosts: ta5k
  gather_facts: no
  become: yes  # Escalate privilege

  tasks:
    - name: Execute show run command
      ios_command:
        commands: "show run"
      register: show_running_configuration_output

    - name: Display show run output
      debug:
        var: show_running_configuration_output.stdout_lines
