# ---
# - name: Backup Adtran OLT Running Configuration
#   hosts: ta5k  # Replace with the hostname or group name for your router(s)
#   gather_facts: no
#   become: yes

#   tasks:
#     - name: Gather Running Configuration
#       ios_command:
#         commands:
#           - show running-config
#       register: running_config
#       become: yes  # Use 'yes' if you need elevated privileges

#     - name: Gather Hostname
#       ios_command:
#         commands:
#           - show snmp | include Chassis
#       register: hostname
#       become: yes  # Use 'yes' if you need elevated privilege

#     - name: Display Hostname
#       debug:
#         var: hostname.stdout_lines

#     - name: Parse Hostname
#       set_fact:
#         extracted_hostname: "{{ hostname_lines[0].split()[-1] }}"
#       vars:
#         hostname_lines: "{{ hostname.stdout_lines[0] }}"

#     - name: Display Extracted Hostname
#       debug:
#         var: extracted_hostname

#     - name: Save Running Configuration to a file using Hostname
#       copy:
#         content: "{{ running_config.stdout_lines[0] }}"
#         dest: "/etc/ansible/adtran_backup_configurations/{{ extracted_hostname }}_running_config.cfg"
#       when: running_config is defined
#       become: no

---
- name: Backup Adtran OLT Running Configuration
  hosts: ta5k  # Replace with the hostname or group name for your router(s)
  gather_facts: no
  become: yes

  tasks:
    - name: Gather Running Configuration
      ios_command:
        commands:
          - show running-config
      register: running_config
      become: yes  # Use 'yes' if you need elevated privileges

    - name: Gather Hostname
      ios_command:
        commands:
          - show snmp | include Chassis
      register: hostname
      become: yes  # Use 'yes' if you need elevated privilege

    - name: Display Hostname
      debug:
        var: hostname.stdout_lines

    - name: Parse Hostname
      set_fact:
        extracted_hostname: "{{ hostname_lines[0].split()[-1] }}"
      vars:
        hostname_lines: "{{ hostname.stdout_lines[0] }}"

    - name: Display Extracted Hostname
      debug:
        var: extracted_hostname

    - name: Process Running Configuration
      set_fact:
        processed_config: "{{ running_config.stdout[0] | replace(',', '\n') | replace('\"', '') }}"

    - name: Save Running Configuration to a file using Hostname
      copy:
        content: "{{ processed_config }}"
        dest: "/etc/ansible/adtran_backup_configurations/{{ extracted_hostname }}_running_config.cfg"
      when: running_config is defined
      become: no

