---
- name: Show Table Voice User SIP
  hosts: ta5k
  gather_facts: no
  become: yes

  tasks:
    - name: Execute command
      ios_command:
        commands: "show table voice user sip"
      register: show_table_voice_user_output

    - name: Display Show Table Voice User SIP output
      debug:
        var: show_table_voice_user_output.stdout_lines