---
- name: Execute "show table voice user sip" Command on Adtran Device
  hosts: ta5k
  gather_facts: no
  tasks:
    - name: Execute Show Table Voice User SIP
      ios_command:
        commands: "show table voice user sip"
      register: show_table_voice_user_sip_output

    - name: Display Show Table Voice User SIP
      debug:
        var: show_table_voice_user_sip_output.stdout_lines

