---
- name: Show Running Configuration of EVC
  hosts: ta5k
  gather_facts: no
  tasks:
    - name: Execute Show Running-Config EVC Command
      ios_command:   # Replace with the appropriate module for your network device
        commands: "show running-config evc"
      register: evc_running_config

    - name: Display Running Configuration of EVC
      debug:
        var: evc_running_config.stdout_lines