---
- name: Execute "show run evc-map" Command
  hosts: ta5k
  gather_facts: no
  become: yes
  
  tasks:
    - name: Execute Show Run EVC-Map
      ios_command:
        commands: "show run evc-map"
      register: show_run_evc_output

    - name: Display Show Run EVC-Map
      debug:
        var: show_run_evc_output.stdout_lines

# Add additional tasks or handlers as needed
