---
- name: Configure ADTRAN Device
  hosts: ta5k  # Replace with the target device hostname or IP address
  gather_facts: no
  connection: network_cli
  become: yes

  tasks:
    - name: Configure AAA Authentication
      ios_command:
        commands:
          - conf t
          - aaa authentication login default group radius local
