---
- name: Configure ADTRAN Device
  hosts: ta5k
  gather_facts: no
  become: yes

  tasks:
    - name: Configure Default Gateway
      ios_command:
        commands:
          - conf t
          - ip default-gateway 10.96.99.254
