---
- name: Configure ADTRAN Device
  hosts: ta5k  # Replace with the target device hostname or IP address
  gather_facts: no
  connection: network_cli
  become: yes

  tasks:
    - name: Configure LACP Response Mode
      ios_command:
        commands:
          - conf t
          - lacp response-mode 1/A reporter-only