---
- name: Configure ADTRAN Device
  hosts: ta5k  # Replace with the target device hostname or IP address
  gather_facts: no
  connection: network_cli
  become: yes

  tasks:
    - name: Configure Voice Conference and SIP Trunk
      ios_command:
        commands:
          - conf t
          - voice conference mode local
          - voice conference local originator flashhook split
          - voice sip-trunk T01
          - sip proxy primary 10.202.0.150
          - sip registrar primary 10.202.0.150
          - domain "10.202.0.150"